type Query {
  profile: Profile
}

type Profile {
  tweets: [Tweet]
  recommendedUsers: [User]
}

type User {
  id: String
  screenName: String
  url: String
  profileImageUrl: String
}

type Category {
  name: String
}

type Topic {
  name: String
  category: Category
}

type Tweet {
  id: ID
  user: User
  createdAt: String
  fullText: String
  favoriteCount: Int
  replyCount: Int
  retweetCount: Int
  quoteCount: Int
}

type Mutation {
  addTweet(fullText: String): Tweet
}
